## makeCacheMatrix creats a function and stores the inverse in a cache


makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  ## Sets the value of the function
    set <- function(y) {
    x <<- y
    m <<- NULL
  }
  
  get <- function() x
  ##Solves the matrix for inverse and stores in the cache
  setinv <- function(solve) m <<- solve
  getinv <- function() m
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)

}


## cacheSolve solves the matrix generated by the makeCacheMatrix function
##and checks if the inverse has been calculated or not
## if it is calculated then it retrieves from the cache else calculates again 

cacheSolve <- function(x=matrix(), ...) {
        ## Return a matrix that is the inverse of 'x'
  
  m <- x$getinv()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  invmatrix <- x$get()
  m <- solve(invmatrix, ...)
  x$setinv(m)
  m

}
